/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobiblioteca;

import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class Principal extends javax.swing.JFrame {
    //Se debe indicar la cantidad máxima de libros de la biblioteca
    final int MAX_LIBROS=50;
    
    //Se declaran las instancias de las estructuras
    ArregloLibros libros = new ArregloLibros(MAX_LIBROS);
    ListaClientes clientes = new ListaClientes();
    ColaReservaciones reservaciones = new ColaReservaciones();
    
    //Se inicializan las interfaces
    FrameBuscarCliente buscarCliente = new FrameBuscarCliente(this);
    FrameRegistrarCliente registrarCliente = new FrameRegistrarCliente(this);
    FrameRegistrarReservacion registrarReservacion = new FrameRegistrarReservacion(this);
    FrameBuscarReservacion eliminarReservacion = new FrameBuscarReservacion(this);
    FrameRegistrarLibro registrarLibro = new FrameRegistrarLibro(this);
    FrameBuscarLibro buscarLibro = new FrameBuscarLibro(this);
    
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        ventanaPrincipal.add(buscarCliente);
        ventanaPrincipal.add(registrarCliente);
        ventanaPrincipal.add(registrarReservacion);
        ventanaPrincipal.add(eliminarReservacion);
        ventanaPrincipal.add(registrarLibro);
        ventanaPrincipal.add(buscarLibro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnClientes = new javax.swing.JMenu();
        btnRegistrarCliente = new javax.swing.JMenuItem();
        btnConsultarClientes = new javax.swing.JMenuItem();
        btnLibros = new javax.swing.JMenu();
        btnRegistrarLibro = new javax.swing.JMenuItem();
        btnConsultarLibro = new javax.swing.JMenuItem();
        btnReservaciones = new javax.swing.JMenu();
        btnAgregarReservacion = new javax.swing.JMenuItem();
        btnBuscarReservacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout ventanaPrincipalLayout = new javax.swing.GroupLayout(ventanaPrincipal);
        ventanaPrincipal.setLayout(ventanaPrincipalLayout);
        ventanaPrincipalLayout.setHorizontalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        ventanaPrincipalLayout.setVerticalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        btnClientes.setText("Clientes");

        btnRegistrarCliente.setText("Registrar");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        btnClientes.add(btnRegistrarCliente);

        btnConsultarClientes.setText("Buscar");
        btnConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClientesActionPerformed(evt);
            }
        });
        btnClientes.add(btnConsultarClientes);

        jMenuBar1.add(btnClientes);

        btnLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu (1).png"))); // NOI18N
        btnLibros.setText("Libros");

        btnRegistrarLibro.setText("Registrar");
        btnRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLibroActionPerformed(evt);
            }
        });
        btnLibros.add(btnRegistrarLibro);

        btnConsultarLibro.setText("Buscar");
        btnConsultarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarLibroActionPerformed(evt);
            }
        });
        btnLibros.add(btnConsultarLibro);

        jMenuBar1.add(btnLibros);

        btnReservaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill.png"))); // NOI18N
        btnReservaciones.setText("Reservaciones");

        btnAgregarReservacion.setText("Registrar");
        btnAgregarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarReservacionActionPerformed(evt);
            }
        });
        btnReservaciones.add(btnAgregarReservacion);

        btnBuscarReservacion.setText("Buscar");
        btnBuscarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReservacionActionPerformed(evt);
            }
        });
        btnReservaciones.add(btnBuscarReservacion);

        jMenuBar1.add(btnReservaciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        CentrarVentana(registrarCliente);
        registrarCliente.limpiarCasillas();
        registrarCliente.limpiarAreaDeTexto();
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnAgregarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarReservacionActionPerformed
        CentrarVentana(registrarReservacion);
        registrarReservacion.limpiarCasillas();
        registrarReservacion.limpiarAreaDeTexto();
    }//GEN-LAST:event_btnAgregarReservacionActionPerformed

    private void btnRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLibroActionPerformed
        CentrarVentana(registrarLibro);
        registrarLibro.limpiarCasillas();
        registrarLibro.limpiarAreaDeTexto();
    }//GEN-LAST:event_btnRegistrarLibroActionPerformed

    private void btnConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClientesActionPerformed
         CentrarVentana(buscarCliente);
         buscarCliente.limpiarAreaDeTexto();
    }//GEN-LAST:event_btnConsultarClientesActionPerformed

    private void btnBuscarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReservacionActionPerformed
        CentrarVentana(eliminarReservacion);
        eliminarReservacion.limpiarAreaDeTexto();
    }//GEN-LAST:event_btnBuscarReservacionActionPerformed

    private void btnConsultarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarLibroActionPerformed
        CentrarVentana(buscarLibro);
        buscarLibro.limpiarAreaDeTexto();
    }//GEN-LAST:event_btnConsultarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    void CentrarVentana(JInternalFrame frame) {
        cerrarVentanas();
        Dimension dimension = ventanaPrincipal.getSize();
        Dimension Dframe = frame.getSize();
        frame.setLocation((dimension.width - Dframe.width) / 2, (dimension.height - Dframe.height) / 2);
        frame.show();
    }

   void cerrarVentanas() {
        buscarCliente.setVisible(false);
        registrarCliente.setVisible(false);
        registrarReservacion.setVisible(false);
        eliminarReservacion.setVisible(false);
        registrarLibro.setVisible(false);
        buscarLibro.setVisible(false);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAgregarReservacion;
    private javax.swing.JMenuItem btnBuscarReservacion;
    private javax.swing.JMenu btnClientes;
    private javax.swing.JMenuItem btnConsultarClientes;
    private javax.swing.JMenuItem btnConsultarLibro;
    private javax.swing.JMenu btnLibros;
    private javax.swing.JMenuItem btnRegistrarCliente;
    private javax.swing.JMenuItem btnRegistrarLibro;
    private javax.swing.JMenu btnReservaciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane ventanaPrincipal;
    // End of variables declaration//GEN-END:variables
}