/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobiblioteca;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class Principal extends javax.swing.JFrame {
/*
    FrameRegistrarCliente rc = new FrameRegistrarCliente();
    FrameRegistrarProducto rp = new FrameRegistrarProducto();
    FrameRegistrarMateriaPrima rmp = new FrameRegistrarMateriaPrima();
    FrameConsultarCliente consultar = new FrameConsultarCliente();
    FrameRegistrarVenta regVenta = new FrameRegistrarVenta();
    ConsultarVenta consultarVenta = new ConsultarVenta();
    FrameGenerarFacturar generarFactura = new FrameGenerarFacturar();
    FrameConsultarProducto consultarProducto = new FrameConsultarProducto();
    FrameConsultarMatPrima consultarMatPrima = new FrameConsultarMatPrima();
    FrameConsultarFactura consultarFactura = new FrameConsultarFactura();
    FrameAnularFactura anularFactura = new FrameAnularFactura();
    FrameActualizarCliente actualizarCliente  = new FrameActualizarCliente();
    FrameActualizarMatPrima actualizarMatPrima = new FrameActualizarMatPrima();
    FrameActualizarProducto actualizarProducto = new FrameActualizarProducto();
    FrameCrearUsuario crearUsuario = new FrameCrearUsuario();
    FrameActualizarContrasena actualizarContrasena = new FrameActualizarContrasena();   
*/
    final int MAX_LIBROS=5;
    ArregloLibros libros = new ArregloLibros(MAX_LIBROS);
    ListaClientes clientes = new ListaClientes();
    ColaReservaciones reservaciones = new ColaReservaciones();
    
    
    
    FrameBuscarCliente buscarCliente = new FrameBuscarCliente(this);
    FrameRegistrarCliente registrarCliente = new FrameRegistrarCliente(this);
    FrameRegistrarReservacion registrarReservacion = new FrameRegistrarReservacion(this);
    FrameBuscarReservacion eliminarReservacion = new FrameBuscarReservacion(this);
    FrameRegistrarLibro registrarLibro = new FrameRegistrarLibro(this);
    FrameBuscarLibro buscarLibro = new FrameBuscarLibro(this);
    
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        /*
        ventanaPrincipal.add(rc);
        ventanaPrincipal.add(rp);
        ventanaPrincipal.add(rmp);
        ventanaPrincipal.add(consultar);
        ventanaPrincipal.add(regVenta);
        ventanaPrincipal.add(consultarVenta);
        ventanaPrincipal.add(generarFactura);
        ventanaPrincipal.add(consultarFactura);
        ventanaPrincipal.add(consultarMatPrima);
        ventanaPrincipal.add(consultarProducto);
        ventanaPrincipal.add(anularFactura);
        ventanaPrincipal.add(actualizarCliente);
        ventanaPrincipal.add(actualizarMatPrima);
        ventanaPrincipal.add(actualizarProducto);
        ventanaPrincipal.add(crearUsuario);
        ventanaPrincipal.add(actualizarContrasena);
        */
        ventanaPrincipal.add(buscarCliente);
        ventanaPrincipal.add(registrarCliente);
        ventanaPrincipal.add(registrarReservacion);
        ventanaPrincipal.add(eliminarReservacion);
        ventanaPrincipal.add(registrarLibro);
        ventanaPrincipal.add(buscarLibro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnClientes = new javax.swing.JMenu();
        btnConsultarClientes = new javax.swing.JMenuItem();
        btnRegistrarCliente = new javax.swing.JMenuItem();
        Productos = new javax.swing.JMenu();
        btnAgregarReservacion = new javax.swing.JMenuItem();
        btnEliminar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnRegistrarLibro = new javax.swing.JMenuItem();
        btnConsultarLibro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout ventanaPrincipalLayout = new javax.swing.GroupLayout(ventanaPrincipal);
        ventanaPrincipal.setLayout(ventanaPrincipalLayout);
        ventanaPrincipalLayout.setHorizontalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        ventanaPrincipalLayout.setVerticalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnConsultarClientes.setText("Buscar");
        btnConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClientesActionPerformed(evt);
            }
        });
        btnClientes.add(btnConsultarClientes);

        btnRegistrarCliente.setText("Registrar");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        btnClientes.add(btnRegistrarCliente);

        jMenuBar1.add(btnClientes);

        Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill.png"))); // NOI18N
        Productos.setText("Reservaciones");
        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });

        btnAgregarReservacion.setText("Agregar");
        btnAgregarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarReservacionActionPerformed(evt);
            }
        });
        Productos.add(btnAgregarReservacion);

        btnEliminar.setText("Buscar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        Productos.add(btnEliminar);

        jMenuBar1.add(Productos);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu (1).png"))); // NOI18N
        jMenu2.setText("Libros");

        btnRegistrarLibro.setText("Registrar");
        btnRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLibroActionPerformed(evt);
            }
        });
        jMenu2.add(btnRegistrarLibro);

        btnConsultarLibro.setText("Buscar");
        btnConsultarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarLibroActionPerformed(evt);
            }
        });
        jMenu2.add(btnConsultarLibro);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed

        CentrarVentana(registrarCliente);
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductosActionPerformed

    private void btnAgregarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarReservacionActionPerformed

        CentrarVentana(registrarReservacion);

    }//GEN-LAST:event_btnAgregarReservacionActionPerformed

    private void btnRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLibroActionPerformed

        CentrarVentana(registrarLibro);
    }//GEN-LAST:event_btnRegistrarLibroActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        //CentrarVentana(rc);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClientesActionPerformed
         CentrarVentana(buscarCliente);
    }//GEN-LAST:event_btnConsultarClientesActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        CentrarVentana(eliminarReservacion);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarLibroActionPerformed
        CentrarVentana(buscarLibro);
    }//GEN-LAST:event_btnConsultarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    void CentrarVentana(JInternalFrame frame) {
        cerrarVentanas();
        Dimension dimension = ventanaPrincipal.getSize();
        Dimension Dframe = frame.getSize();
        frame.setLocation((dimension.width - Dframe.width) / 2, (dimension.height - Dframe.height) / 2);
        frame.show();
        

    }

   void cerrarVentanas() {////
        
       
        buscarCliente.setVisible(false);
        registrarCliente.setVisible(false);
        registrarReservacion.setVisible(false);
        eliminarReservacion.setVisible(false);
        registrarLibro.setVisible(false);
        buscarLibro.setVisible(false);
       /*
        generarFactura.setVisible(false);
        consultarFactura.setVisible(false);
        consultarMatPrima.setVisible(false);
        consultarProducto.setVisible(false);
        anularFactura.setVisible(false);
        actualizarCliente.setVisible(false);
        actualizarMatPrima.setVisible(false);
        actualizarProducto.setVisible(false);
        crearUsuario.setVisible(false);
        actualizarContrasena.setVisible(false);
        */
       
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Productos;
    private javax.swing.JMenuItem btnAgregarReservacion;
    private javax.swing.JMenu btnClientes;
    private javax.swing.JMenuItem btnConsultarClientes;
    private javax.swing.JMenuItem btnConsultarLibro;
    private javax.swing.JMenuItem btnEliminar;
    private javax.swing.JMenuItem btnRegistrarCliente;
    private javax.swing.JMenuItem btnRegistrarLibro;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane ventanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
